@baseUrl = http://localhost:3333
# @authToken = {{authenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Bruno Rodrigues",
  "email": "bruno@example.com.br",
  "role": "admin",
  "password": "123456"
}